
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "ALWAYS AND FLOAT NAME POSITION_X POSITION_Yoperator : ALWAYS '(' '(' '(' POSITION_X NAME ')' '>' FLOAT ')' AND '(' '(' POSITION_Y NAME ')' '>' FLOAT ')' ')'\n    "
    
_lr_action_items = {'ALWAYS':([0,],[2,]),'$end':([1,21,],[0,-1,]),'(':([2,3,4,12,13,],[3,4,5,13,14,]),'POSITION_X':([5,],[6,]),'NAME':([6,15,],[7,16,]),')':([7,10,16,19,20,],[8,11,17,20,21,]),'>':([8,17,],[9,18,]),'FLOAT':([9,18,],[10,19,]),'AND':([11,],[12,]),'POSITION_Y':([14,],[15,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'operator':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> operator","S'",1,None,None,None),
  ('operator -> ALWAYS ( ( ( POSITION_X NAME ) > FLOAT ) AND ( ( POSITION_Y NAME ) > FLOAT ) )','operator',20,'p_test','language_yacc.py',8),
]
