name: Tests Docker
on: [push]
jobs:
  tests-docker:
    runs-on: ubuntu-20.04
    steps:
      - run: echo "Test"
      - run: docker build -t test .
      - run: docker run test python3.8 unit_tests/unit_test.py
